name: rundeck-k8s-nodes
version: 1.0.0
rundeckPluginVersion: 1.2
author: bluecontainer
description: Kubernetes workload discovery for Rundeck node source
url: https://github.com/bluecontainer/kubectl-rundeck-nodes
license: Apache-2.0
tags:
  - kubernetes
  - k8s
  - workload
  - nodes
  - discovery
providers:
  - name: k8s-workload-nodes
    service: ResourceModelSource
    title: Kubernetes Workload Nodes
    description: |-
      Discovers Kubernetes workloads (Helm releases, StatefulSets, Deployments)
      as Rundeck nodes with targeting attributes for kubectl plugins.
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: nodes.sh
    resource-format: resourcejson
    config:
      - name: k8s_token
        type: String
        title: Kubernetes Token
        description: ServiceAccount token for K8s API access (select from Key Storage)
        required: true
        scope: Instance
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
      - name: k8s_url
        type: String
        title: Kubernetes API URL
        description: "Kubernetes API server URL (e.g., https://kubernetes.default.svc)"
        required: true
        scope: Instance
      - name: namespace
        type: String
        title: Namespace
        description: Namespace to discover workloads in (empty = all namespaces)
        required: false
        scope: Instance
      - name: label_selector
        type: String
        title: Label Selector
        description: "Filter workloads by labels (e.g., app=myapp)"
        required: false
        scope: Instance
      - name: execution_mode
        type: Select
        title: Execution Mode
        description: How to run the kubectl plugin
        required: true
        scope: Instance
        default: native
        values:
          - native
          - docker
          - kubernetes
      - name: docker_image
        type: String
        title: Docker Image
        description: Image containing kubectl-rundeck-nodes (docker/kubernetes mode)
        required: false
        scope: Instance
        default: bluecontainer/kubectl-rundeck-nodes:latest
      - name: docker_network
        type: String
        title: Docker Network
        description: Docker network to use (docker mode only)
        required: false
        scope: Instance
        default: host
      - name: plugin_namespace
        type: String
        title: Plugin Namespace
        description: Namespace to run plugin pod in (kubernetes mode only)
        required: false
        scope: Instance
        default: default
      - name: service_account
        type: String
        title: Service Account
        description: ServiceAccount for plugin pod (kubernetes mode only)
        required: false
        scope: Instance
        default: default
      - name: image_pull_policy
        type: Select
        title: Image Pull Policy
        description: Image pull policy for plugin pod (kubernetes mode only)
        required: false
        scope: Instance
        default: IfNotPresent
        values:
          - Always
          - IfNotPresent
          - Never
      - name: cluster_name
        type: String
        title: Cluster Name
        description: Cluster identifier for multi-cluster discovery
        required: false
        scope: Instance
      - name: cluster_token_suffix
        type: String
        title: Cluster Token Suffix
        description: "Key Storage path suffix for this cluster's token (e.g., clusters/prod/token)"
        required: false
        scope: Instance
      - name: default_token_suffix
        type: String
        title: Default Token Suffix
        description: Default Key Storage path suffix when not using multi-cluster
        required: false
        scope: Instance
        default: rundeck/k8s-token
      # Phase 1: Core Filtering Options
      - name: types
        type: String
        title: Workload Types
        description: "Only include these workload types (comma-separated: helm-release, statefulset, deployment)"
        required: false
        scope: Instance
      - name: exclude_types
        type: String
        title: Exclude Types
        description: "Exclude these workload types (comma-separated)"
        required: false
        scope: Instance
      - name: exclude_labels
        type: String
        title: Exclude Labels
        description: "Exclude workloads matching these labels (comma-separated selectors, e.g., app=operator,tier=control-plane)"
        required: false
        scope: Instance
      - name: exclude_operator
        type: Boolean
        title: Exclude Operator
        description: Exclude operator controller-manager workloads
        required: false
        scope: Instance
        default: "true"
      - name: healthy_only
        type: Boolean
        title: Healthy Only
        description: Only include workloads with all pods running
        required: false
        scope: Instance
        default: "false"
      - name: unhealthy_only
        type: Boolean
        title: Unhealthy Only
        description: Only include workloads with some pods not running
        required: false
        scope: Instance
        default: "false"
      # Phase 2: Pattern Matching Options
      - name: name_pattern
        type: String
        title: Name Pattern
        description: "Only include workloads matching these glob patterns (comma-separated, e.g., myapp-*)"
        required: false
        scope: Instance
      - name: exclude_pattern
        type: String
        title: Exclude Pattern
        description: "Exclude workloads matching these glob patterns (comma-separated)"
        required: false
        scope: Instance
      - name: exclude_namespaces
        type: String
        title: Exclude Namespaces
        description: "Exclude workloads in these namespaces (comma-separated)"
        required: false
        scope: Instance
      - name: namespace_pattern
        type: String
        title: Namespace Pattern
        description: "Only include workloads in namespaces matching these patterns (comma-separated)"
        required: false
        scope: Instance
      - name: exclude_namespace_pattern
        type: String
        title: Exclude Namespace Pattern
        description: "Exclude workloads in namespaces matching these patterns (comma-separated)"
        required: false
        scope: Instance
      # Phase 4: Output Customization Options
      - name: add_tags
        type: String
        title: Add Tags
        description: "Add custom tags to all nodes (comma-separated, e.g., env:prod,team:platform)"
        required: false
        scope: Instance
      - name: labels_as_tags
        type: String
        title: Labels as Tags
        description: "Convert these Kubernetes labels to Rundeck tags (comma-separated, e.g., app.kubernetes.io/name)"
        required: false
        scope: Instance
      - name: label_attributes
        type: String
        title: Label Attributes
        description: "Add these Kubernetes labels as node attributes (comma-separated, e.g., app.kubernetes.io/version)"
        required: false
        scope: Instance
      - name: annotation_attributes
        type: String
        title: Annotation Attributes
        description: "Add these Kubernetes annotations as node attributes (comma-separated)"
        required: false
        scope: Instance
      # Phase 5: Pod Discovery Options
      - name: include_pods
        type: Boolean
        title: Include Pods
        description: Include individual pods as nodes (in addition to workloads)
        required: false
        scope: Instance
        default: "false"
      - name: pods_only
        type: Boolean
        title: Pods Only
        description: Only return pod nodes, excluding workload-level nodes (implies Include Pods)
        required: false
        scope: Instance
        default: "false"
      - name: pod_status
        type: String
        title: Pod Status
        description: "Only include pods with these phases (comma-separated, e.g., Running,Pending)"
        required: false
        scope: Instance
      - name: pod_name_pattern
        type: String
        title: Pod Name Pattern
        description: "Only include pods matching these glob patterns (comma-separated, e.g., *-0 for first StatefulSet replica)"
        required: false
        scope: Instance
      - name: pod_ready_only
        type: Boolean
        title: Pod Ready Only
        description: Only include pods where all containers are ready
        required: false
        scope: Instance
        default: "false"
      - name: max_pods_per_workload
        type: Integer
        title: Max Pods Per Workload
        description: Maximum number of pod nodes per workload (0 = unlimited)
        required: false
        scope: Instance
        default: "0"
